### ISSUE TITLE
Apresentação da aplicação para Gerenciamento de Riscos com funcionalidades CRUD de acordo com modelo UML/ER proposto

### ISSUE THREAD

**Issue by evaldo** [evaldo/historyrisk#2]
George me responda nesta ISSUE se está recebendo os emails do Git.

**Comment by GeorgeSamarino** [comment]
Evaldo, boa noite.


Estou com algum problema para utilizar este sistema. Podemos marcar para verificar se está configurado corretamente em minha máquina?


Abs.


George Samarino
e-mail: george.samarino@hotmail.com
Celular: (32) 9 8426 - 9809


________________________________
De: Evaldo de Oliveira <notifications@github.com>
Enviado: segunda-feira, 17 de abril de 2017 11:32
Para: evaldo/historyrisk
Cc: Subscribed
Assunto: [evaldo/historyrisk] Apresentação da aplicação para Gerenciamento de Riscos com funcionalidades CRUD de acordo com modelo UML/ER proposto (#2)


George me responda nesta ISSUE se está recebendo os emails do Git.
