### ISSUE TITLE
Criar tela de login e implementar nova versão de banco de dados

### ISSUE THREAD

**Issue by evaldo** [evaldo/historyrisk#3]
Criar tela de login e implementar nova versão de banco de dados.

**Comment by GeorgeSamarino** [comment]
Evaldo, bom dia.
Terminei de fazer a tela de login e a sessão. Quero fazer algumas mudanças na base de dados. Quando podemos falar sobre isso?

Abs.

George Samarino
e-mail: george.samarino@hotmail.com
Celular: (32) 9 8426 - 9809

Em 2 de mai de 2017 20:18, Evaldo de Oliveira <notifications@github.com> escreveu:

Criar tela de login e implementar nova versão de banco de dados.
